<template>
  <aside>
    上传电子书步骤：首先上传epub电子书文件，服务器对电子书进行解析，解析成功后会将电子书的信息自动填充表单，之后需手动点击新增电子书完成电子书的保存。
    <a
      href="http://www.youaobao.xyz/admin-docs/"
      target="_blank"
    >课程官网</a>
    获取更多开发引导
  </aside>
</template>
